spring.application.name=Landmark-Nearby
server.port=8086

# rabbit
spring.rabbitmq.host=${RABBIT_HOST}
spring.rabbitmq.port=${RABBIT_PORT}
spring.rabbitmq.username=${RABBIT_USER_NAME}
spring.rabbitmq.password=${RABBIT_PASSWORD}

# rabbit queue
landmark.request.queue=landmark.request.queue
landmark.response.queue=landmark.response.queue
