apiVersion: v1
kind: Secret
metadata:
  name: postgres-exporter-secret
  namespace: landmark
type: Opaque
stringData:
  POSTGRES_DB: "landmark_db"
  POSTGRES_MONITORING_USER: "landmark_monitoring_user"
  POSTGRES_MONITORING_PASSWORD: "landmark_monitoring_password"
