apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: landmark
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
    - name: management
      port: 15672
      nodePort: 31672
    - name: metrics
      port: 15692