apiVersion: v1
kind: Service
metadata:
  name: landmark-nearby
  namespace: landmark
spec:
  type: NodePort
  #type: ClusterIP
  selector:
    app: landmark-nearby
  ports:
    - port: 8086
      nodePort: 30086
      targetPort: 8086
