apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'rabbitmq'
        static_configs:
          - targets: ['rabbitmq.landmark.svc.cluster.local:15692']

      - job_name: 'landmark-services'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets:
              - 'landmark-geo-query-engine.landmark.svc.cluster.local:8087'
              - 'landmark-nearby.landmark.svc.cluster.local:8086'
              - 'landmark-nearify.landmark.svc.cluster.local:8084'

#      - job_name: 'postgres-exporter'
#        static_configs:
#          - targets: ['postgres-exporter.landmark.svc.cluster.local:9187']