version: "3.9"

services:
  # -------------------------
  # RABBITMQ (WITH PROMETHEUS)
  # -------------------------
  rabbitmq:
    image: rabbitmq:4.2.3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
      - "15692:15692"   # Grafana/Prometheus
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    command: >
      bash -c "rabbitmq-plugins enable --offline rabbitmq_prometheus &&
               rabbitmq-server"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - landmark-net

  # -------------------------
  # POSTGRES + PGRouting
  # -------------------------
  postgres_pgrouting:
    image: pgrouting/pgrouting:16-3.5-4.0
    container_name: postgres_pgrouting
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/db:/var/lib/postgresql/data
      - ./postgres/logs:/logs
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_MONITORING_USER: ${POSTGRES_MONITORING_USER}
      POSTGRES_MONITORING_PASSWORD: ${POSTGRES_MONITORING_PASSWORD}
      #PGDATA: /data/postgres
    networks:
      - landmark-net

  # -------------------------
  # POSTGRES EXPORTER
  # -------------------------
  postgres-exporter:
    #image: prometheuscommunity/postgres-exporter
    image: prometheuscommunity/postgres-exporter:v0.19.0
    container_name: postgres-exporter
    ports:
      - "9187:9187"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_MONITORING_USER: ${POSTGRES_MONITORING_USER}
      POSTGRES_MONITORING_PASSWORD: ${POSTGRES_MONITORING_PASSWORD}
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_MONITORING_USER}:${POSTGRES_MONITORING_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
    depends_on:
      - postgres_pgrouting
    networks:
      - landmark-net

  importer:
    build: importer
    container_name: importer
    depends_on:
      - postgres_pgrouting
    volumes:
      - ./postgres/data:/data
    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - landmark-net
    command:
      - bash
      - -c
      - |
        set -e

        echo "Waiting for PostgreSQL..."
        until pg_isready -h postgres_pgrouting -p 5432 -U landmark_user; do
          sleep 2
        done

        echo "PostgreSQL is ready. Starting import..."

        echo "********************************"
        echo "Starting osm2pgrouting import..."
        echo "********************************"

        osm2pgrouting -f /data/map.osm \
          -d landmark_db \
          -U landmark_user \
          -W "$POSTGRES_PASSWORD" \
          -h postgres_pgrouting \
          --clean

        EXIT_OSM_2_PGROUTING=$$?

        if [ $$EXIT_OSM_2_PGROUTING -eq 0 ]; then
          echo "Exit code $$EXIT_OSM_2_PGROUTING"
          echo "Import of osm2pgrouting finished successfully!"
        else
          echo "Import of osm2pgrouting failed with exit code $$EXIT_OSM_2_PGROUTING"
          exit 1
        fi

        echo "********************************"
        echo "Starting osm2pgsql import..."
        echo "********************************"

        osm2pgsql \
          -H postgres_pgrouting \
          -d landmark_db \
          -U landmark_user \
          --create \
          --slim \
          --hstore \
          /data/map.osm

        EXIT_OSM_2_PGSSQL=$$?

        if [ $$EXIT_OSM_2_PGSSQL -eq 0 ]; then
          echo "$$EXIT_OSM_2_PGSSQL"
          echo "Import of osm2pgsql finished successfully!"
        else
          echo "Import of osm2pgsql failed with exit code $$EXIT_OSM_2_PGSSQL"
          exit 1
        fi

        echo "All Import finished successfully!"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    #restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - landmark-net

  # -------------------------
  # PROMETHEUS
  # -------------------------
  prometheus:
    image: prom/prometheus:v3.5.1
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - landmark-net

  # -------------------------
  # GRAFANA
  # -------------------------
  grafana:
    image: grafana/grafana:12.3
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - landmark-net

  landmark-nearify:
    image: landmark-nearify
    container_name: landmark-nearify
    profiles:
      - landmark
    ports:
      - "8084:8084"
    environment:
      LANDMARK_NEARBY_API_URL: http://host.docker.internal:8086/api/landmark/nearby
    depends_on:
      - postgres_pgrouting
      - rabbitmq
    networks:
      - landmark-net

  landmark-nearby:
    image: landmark-nearby
    container_name: landmark-nearby
    profiles:
      - landmark
    ports:
      - "8086:8086"
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USER_NAME: 'guest'
      RABBIT_PASSWORD: 'guest'
    depends_on:
      - postgres_pgrouting
      - rabbitmq
    networks:
      - landmark-net

  landmark-geo-query-engine:
    image: landmark-geo-query-engine
    container_name: landmark-geo-query-engine
    profiles:
      - landmark
    ports:
      - "8087:8087"
    environment:
      DB_HOST: postgres_pgrouting
      DB_PORT: 5432
      DB_NAME: 'landmark_db'
      DB_USER_NAME: 'landmark_user'
      DB_USER_PASSWORD: 'landmark_password'
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USER_NAME: 'guest'
      RABBIT_PASSWORD: 'guest'
    depends_on:
      - postgres_pgrouting
      - rabbitmq
    networks:
      - landmark-net

volumes:
  rabbitmq_data:
  prometheus_data:
  grafana_data:

networks:
  landmark-net:
    driver: bridge