version: "3.9"

services:

  landmark-osm-fetch-local:
      image: landmark-osm-fetch-local
      container_name: landmark-osm-fetch-local
      volumes:
        - ./../_postgres/data:/data
        - ./../_postgres/data/pbf:/data/pbf
        - ./../_postgres/data/osm:/data/osm
      environment:
        OSM_URL: "https://download.geofabrik.de/europe/sweden-latest.osm.pbf"
        OSM_PBF: "sweden-latest.osm.pbf"
        EXTRACT_BBOX: "11.80,57.60,12.10,57.80"
        #EXTRACT_BBOX: "11.80,57.60,11.85,57.65"
        EXTRACT_PBF: "gothenburg.osm.pbf"
        EXTRACT_OSM: "gothenburg.osm"
        RELEASE_OSM: "release/map.osm"
      networks:
        - landmark-shared-net

networks:
  landmark-shared-net:
    external: true