version: "3.9"

services:

  landmark-osm-importer:
      image: landmark-osm-importer
      container_name: landmark_osm_importer
      volumes:
        - ./postgres/data:/data
      environment:
        PGPASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      networks:
        - landmark-shared-net
      command:
        - bash
        - -c
        - |
          set -e

          echo "Waiting for PostgreSQL..."
          until pg_isready -h postgres_pgrouting -p 5432 -U landmark_user; do
            sleep 2
          done

          echo "PostgreSQL is ready. Starting import..."

          echo "********************************"
          echo "Starting osm2pgrouting import..."
          echo "********************************"

          osm2pgrouting -f /data/map.osm \
            -d landmark_db \
            -U landmark_user \
            -W "$POSTGRES_PASSWORD" \
            -h postgres_pgrouting \
            --clean

          EXIT_OSM_2_PGROUTING=$$?

          if [ $$EXIT_OSM_2_PGROUTING -eq 0 ]; then
            echo "Exit code $$EXIT_OSM_2_PGROUTING"
            echo "Import of osm2pgrouting finished successfully!"
          else
            echo "Import of osm2pgrouting failed with exit code $$EXIT_OSM_2_PGROUTING"
            exit 1
          fi

          echo "********************************"
          echo "Starting osm2pgsql import..."
          echo "********************************"

          osm2pgsql \
            -H postgres_pgrouting \
            -d landmark_db \
            -U landmark_user \
            --create \
            --slim \
            --hstore \
            /data/map.osm

          EXIT_OSM_2_PGSSQL=$$?

          if [ $$EXIT_OSM_2_PGSSQL -eq 0 ]; then
            echo "$$EXIT_OSM_2_PGSSQL"
            echo "Import of osm2pgsql finished successfully!"
          else
            echo "Import of osm2pgsql failed with exit code $$EXIT_OSM_2_PGSSQL"
            exit 1
          fi

          echo "All Import finished successfully!"

networks:
  landmark-shared-net:
    external: true