apiVersion: v1
kind: Service
metadata:
  name: landmark-nearify
  namespace: landmark
spec:
  type: NodePort
  #type: ClusterIP
  selector:
    app: landmark-nearify
  ports:
    - port: 8084
      nodePort: 30084
      #targetPort: 8084
