apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: landmark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secret
                  key: PGADMIN_DEFAULT_EMAIL
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secret
                  key: PGADMIN_DEFAULT_PASSWORD
            - name: PGADMIN_DEFAULT_SERVER
              value: "postgres-0.postgres.landmark.svc.cluster.local"
            - name: PGADMIN_CONFIG_SERVER_MODE
              value: "False"
          volumeMounts:
            - name: pgadmin-config-volume
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
      volumes:
        - name: pgadmin-config-volume
          configMap:
            name: pgadmin-config