FROM debian:bookworm-slim

# Install wget
# Install osmium
RUN apt-get update && apt-get install -y \
    wget \
    osmium-tool \
    # ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Create data directory
RUN mkdir -p /data
RUN mkdir -p /data/pbf
RUN mkdir -p /data/osm


# Copy the import script into the image
COPY osm_download.sh /usr/local/bin/osm_download.sh
RUN chmod +x /usr/local/bin/osm_download.sh

# Set working directory
WORKDIR /data

# Default command runs the import script
CMD ["/usr/local/bin/osm_download.sh"]