package com.joda.landmark.geoqueryengine.messaging.dto;

public enum AmenitySubCategory {

  // Food & Drink
  RESTAURANT(AmenityCategory.FOOD_AND_DRINK),
  CAFE(AmenityCategory.FOOD_AND_DRINK),
  BAR(AmenityCategory.FOOD_AND_DRINK),
  FAST_FOOD(AmenityCategory.FOOD_AND_DRINK),
  ICE_CREAM(AmenityCategory.FOOD_AND_DRINK),
  FOOD_COURT(AmenityCategory.FOOD_AND_DRINK),
  PUB(AmenityCategory.FOOD_AND_DRINK),
  BBQ(AmenityCategory.FOOD_AND_DRINK),

  // Accommodation
  HOTEL(AmenityCategory.ACCOMMODATION),
  LOUNGE(AmenityCategory.ACCOMMODATION),
  SPA(AmenityCategory.ACCOMMODATION),

  // Health & Emergency
  HOSPITAL(AmenityCategory.HEALTH_AND_EMERGENCY),
  CLINIC(AmenityCategory.HEALTH_AND_EMERGENCY),
  DOCTORS(AmenityCategory.HEALTH_AND_EMERGENCY),
  DENTIST(AmenityCategory.HEALTH_AND_EMERGENCY),
  FIRST_AID(AmenityCategory.HEALTH_AND_EMERGENCY),
  BLOOD_DONATION(AmenityCategory.HEALTH_AND_EMERGENCY),
  PHARMACY(AmenityCategory.HEALTH_AND_EMERGENCY),
  RESCUE_STATION(AmenityCategory.HEALTH_AND_EMERGENCY),
  FIRE_STATION(AmenityCategory.HEALTH_AND_EMERGENCY),
  LIFEBUAT_STATION(AmenityCategory.HEALTH_AND_EMERGENCY),

  // Education
  SCHOOL(AmenityCategory.EDUCATION),
  COLLEGE(AmenityCategory.EDUCATION),
  UNIVERSITY(AmenityCategory.EDUCATION),
  KINDERGARTEN(AmenityCategory.EDUCATION),
  DRIVING_SCHOOL(AmenityCategory.EDUCATION),
  TRAINING(AmenityCategory.EDUCATION),
  TOY_LIBRARY(AmenityCategory.EDUCATION),
  DANCING_SCHOOL(AmenityCategory.EDUCATION),
  STUDIO(AmenityCategory.EDUCATION),

  // Arts, Culture & Entertainment
  ARTS_CENTRE(AmenityCategory.ARTS_CULTURE_ENTERTAINMENT),
  CULTURE_CENTER(AmenityCategory.ARTS_CULTURE_ENTERTAINMENT),
  CONCERT_HALL(AmenityCategory.ARTS_CULTURE_ENTERTAINMENT),
  MUSIC_VENUE(AmenityCategory.ARTS_CULTURE_ENTERTAINMENT),
  THEATRE(AmenityCategory.ARTS_CULTURE_ENTERTAINMENT),
  CINEMA(AmenityCategory.ARTS_CULTURE_ENTERTAINMENT),
  EVENTS_CENTRE(AmenityCategory.ARTS_CULTURE_ENTERTAINMENT),
  EVENTS_VENUE(AmenityCategory.ARTS_CULTURE_ENTERTAINMENT),

  // Shopping & Services
  SHOPPING_MALL(AmenityCategory.SHOPPING_AND_SERVICES),
  MARKETPLACE(AmenityCategory.SHOPPING_AND_SERVICES),
  FREESHOP(AmenityCategory.SHOPPING_AND_SERVICES),
  REUSE(AmenityCategory.SHOPPING_AND_SERVICES),
  RECYCLING(AmenityCategory.SHOPPING_AND_SERVICES),
  PARCEL_LOCKER(AmenityCategory.SHOPPING_AND_SERVICES),
  RENTAL_MACHINE(AmenityCategory.SHOPPING_AND_SERVICES),
  LOCKER(AmenityCategory.SHOPPING_AND_SERVICES),
  LUGGAGE_LOCKER(AmenityCategory.SHOPPING_AND_SERVICES),
  POST_OFFICE(AmenityCategory.SHOPPING_AND_SERVICES),
  POST_BOX(AmenityCategory.SHOPPING_AND_SERVICES),
  LETTER_BOX(AmenityCategory.SHOPPING_AND_SERVICES),
  PHOTO_BOOTH(AmenityCategory.SHOPPING_AND_SERVICES),
  BUREAU_DE_CHANGE(AmenityCategory.SHOPPING_AND_SERVICES),

  // Transport & Vehicle
  ATM(AmenityCategory.TRANSPORT_AND_VEHICLE),
  CAR_RENTAL(AmenityCategory.TRANSPORT_AND_VEHICLE),
  CAR_WASH(AmenityCategory.TRANSPORT_AND_VEHICLE),
  VEHICLE_INSPECTION(AmenityCategory.TRANSPORT_AND_VEHICLE),
  CHARGING_STATION(AmenityCategory.TRANSPORT_AND_VEHICLE),
  COMPRESSED_AIR(AmenityCategory.TRANSPORT_AND_VEHICLE),
  BICYCLE_PARKING(AmenityCategory.TRANSPORT_AND_VEHICLE),
  BICYCLE_RENTAL(AmenityCategory.TRANSPORT_AND_VEHICLE),
  BICYCLE_REPAIR_STATION(AmenityCategory.TRANSPORT_AND_VEHICLE),
  BOAT_RENTAL(AmenityCategory.TRANSPORT_AND_VEHICLE),
  BOAT_STORAGE(AmenityCategory.TRANSPORT_AND_VEHICLE),
  BUS_STATION(AmenityCategory.TRANSPORT_AND_VEHICLE),
  FERRY_TERMINAL(AmenityCategory.TRANSPORT_AND_VEHICLE),
  TAXI(AmenityCategory.TRANSPORT_AND_VEHICLE),
  PARKING(AmenityCategory.TRANSPORT_AND_VEHICLE),
  PARKING_SPACE(AmenityCategory.TRANSPORT_AND_VEHICLE),
  PARKING_ENTRANCE(AmenityCategory.TRANSPORT_AND_VEHICLE),
  MOTORCYCLE_PARKING(AmenityCategory.TRANSPORT_AND_VEHICLE),
  LOADING_DOCK(AmenityCategory.TRANSPORT_AND_VEHICLE),

  // Animal Services
  ANIMAL_BOARDING(AmenityCategory.ANIMAL_SERVICES),
  ANIMAL_SHELTER(AmenityCategory.ANIMAL_SERVICES),
  ANIMAL_TRAINING(AmenityCategory.ANIMAL_SERVICES),
  VETERINARY(AmenityCategory.ANIMAL_SERVICES),
  HUNTING_STAND(AmenityCategory.ANIMAL_SERVICES),

  // Public Facilities
  BENCH(AmenityCategory.PUBLIC_FACILITIES),
  FOUNTAIN(AmenityCategory.PUBLIC_FACILITIES),
  DRINKING_WATER(AmenityCategory.PUBLIC_FACILITIES),
  WATERING_PLACE(AmenityCategory.PUBLIC_FACILITIES),
  WATER_POINT(AmenityCategory.PUBLIC_FACILITIES),
  GRIT_BIN(AmenityCategory.PUBLIC_FACILITIES),
  SANITARY_DUMP_STATION(AmenityCategory.PUBLIC_FACILITIES),
  SHOWER(AmenityCategory.PUBLIC_FACILITIES),
  TOILETS(AmenityCategory.PUBLIC_FACILITIES),
  PUBLIC_BATH(AmenityCategory.PUBLIC_FACILITIES),
  PUBLIC_BOOKCASE(AmenityCategory.PUBLIC_FACILITIES),
  MEETING_POINT(AmenityCategory.PUBLIC_FACILITIES),
  MUSTER_POINT(AmenityCategory.PUBLIC_FACILITIES),
  TABLE(AmenityCategory.PUBLIC_FACILITIES),
  SMOKING_AREA(AmenityCategory.PUBLIC_FACILITIES),
  THERMOMETER(AmenityCategory.PUBLIC_FACILITIES),
  WEIGHBRIDGE(AmenityCategory.PUBLIC_FACILITIES),

  // Security & Governance
  POLICE(AmenityCategory.SECURITY_AND_GOVERNANCE),
  COURTHOUSE(AmenityCategory.SECURITY_AND_GOVERNANCE),
  LOST_PROPERTY_OFFICE(AmenityCategory.SECURITY_AND_GOVERNANCE),
  RECEPTION_DESK(AmenityCategory.SECURITY_AND_GOVERNANCE),

  // Social & Community
  COMMUNITY_CENTRE(AmenityCategory.SOCIAL_AND_COMMUNITY),
  SOCIAL_CENTRE(AmenityCategory.SOCIAL_AND_COMMUNITY),
  SOCIAL_FACILITY(AmenityCategory.SOCIAL_AND_COMMUNITY),
  COWORKING_SPACE(AmenityCategory.SOCIAL_AND_COMMUNITY),
  CONFERENCE_CENTRE(AmenityCategory.SOCIAL_AND_COMMUNITY),
  CENTRE(AmenityCategory.SOCIAL_AND_COMMUNITY),

  // Nightlife
  NIGHTCLUB(AmenityCategory.NIGHTLIFE);

  private final AmenityCategory parentCategory;

  AmenitySubCategory(AmenityCategory parentCategory) {
    this.parentCategory = parentCategory;
  }

  public AmenityCategory getParentCategory() {
    return parentCategory;
  }
}
