package com.joda.landmark.geoqueryengine.messaging.dto;

public enum AmenityCategory {
  FOOD_AND_DRINK,
  ACCOMMODATION,
  HEALTH_AND_EMERGENCY,
  EDUCATION,
  ARTS_CULTURE_ENTERTAINMENT,
  SHOPPING_AND_SERVICES,
  TRANSPORT_AND_VEHICLE,
  ANIMAL_SERVICES,
  PUBLIC_FACILITIES,
  SECURITY_AND_GOVERNANCE,
  SOCIAL_AND_COMMUNITY,
  NIGHTLIFE
}
