package com.joda.landmark.geoqueryengine.messaging.dto;

public enum SubCategory {

  // Food & Drink
  RESTAURANT(Category.FOOD_AND_DRINK),
  CAFE(Category.FOOD_AND_DRINK),
  BAR(Category.FOOD_AND_DRINK),
  FAST_FOOD(Category.FOOD_AND_DRINK),
  ICE_CREAM(Category.FOOD_AND_DRINK),
  FOOD_COURT(Category.FOOD_AND_DRINK),
  PUB(Category.FOOD_AND_DRINK),
  BBQ(Category.FOOD_AND_DRINK),

  // Accommodation
  HOTEL(Category.ACCOMMODATION),
  LOUNGE(Category.ACCOMMODATION),
  SPA(Category.ACCOMMODATION),

  // Health & Emergency
  HOSPITAL(Category.HEALTH_AND_EMERGENCY),
  CLINIC(Category.HEALTH_AND_EMERGENCY),
  DOCTORS(Category.HEALTH_AND_EMERGENCY),
  DENTIST(Category.HEALTH_AND_EMERGENCY),
  FIRST_AID(Category.HEALTH_AND_EMERGENCY),
  BLOOD_DONATION(Category.HEALTH_AND_EMERGENCY),
  PHARMACY(Category.HEALTH_AND_EMERGENCY),
  RESCUE_STATION(Category.HEALTH_AND_EMERGENCY),
  FIRE_STATION(Category.HEALTH_AND_EMERGENCY),
  LIFEBUAT_STATION(Category.HEALTH_AND_EMERGENCY),

  // Education
  SCHOOL(Category.EDUCATION),
  COLLEGE(Category.EDUCATION),
  UNIVERSITY(Category.EDUCATION),
  KINDERGARTEN(Category.EDUCATION),
  DRIVING_SCHOOL(Category.EDUCATION),
  TRAINING(Category.EDUCATION),
  TOY_LIBRARY(Category.EDUCATION),
  DANCING_SCHOOL(Category.EDUCATION),
  STUDIO(Category.EDUCATION),

  // Arts, Culture & Entertainment
  ARTS_CENTRE(Category.ARTS_CULTURE_ENTERTAINMENT),
  CULTURE_CENTER(Category.ARTS_CULTURE_ENTERTAINMENT),
  CONCERT_HALL(Category.ARTS_CULTURE_ENTERTAINMENT),
  MUSIC_VENUE(Category.ARTS_CULTURE_ENTERTAINMENT),
  THEATRE(Category.ARTS_CULTURE_ENTERTAINMENT),
  CINEMA(Category.ARTS_CULTURE_ENTERTAINMENT),
  EVENTS_CENTRE(Category.ARTS_CULTURE_ENTERTAINMENT),
  EVENTS_VENUE(Category.ARTS_CULTURE_ENTERTAINMENT),

  // Shopping & Services
  SHOPPING_MALL(Category.SHOPPING_AND_SERVICES),
  MARKETPLACE(Category.SHOPPING_AND_SERVICES),
  FREESHOP(Category.SHOPPING_AND_SERVICES),
  REUSE(Category.SHOPPING_AND_SERVICES),
  RECYCLING(Category.SHOPPING_AND_SERVICES),
  PARCEL_LOCKER(Category.SHOPPING_AND_SERVICES),
  RENTAL_MACHINE(Category.SHOPPING_AND_SERVICES),
  LOCKER(Category.SHOPPING_AND_SERVICES),
  LUGGAGE_LOCKER(Category.SHOPPING_AND_SERVICES),
  POST_OFFICE(Category.SHOPPING_AND_SERVICES),
  POST_BOX(Category.SHOPPING_AND_SERVICES),
  LETTER_BOX(Category.SHOPPING_AND_SERVICES),
  PHOTO_BOOTH(Category.SHOPPING_AND_SERVICES),
  BUREAU_DE_CHANGE(Category.SHOPPING_AND_SERVICES),

  // Transport & Vehicle
  ATM(Category.TRANSPORT_AND_VEHICLE),
  CAR_RENTAL(Category.TRANSPORT_AND_VEHICLE),
  CAR_WASH(Category.TRANSPORT_AND_VEHICLE),
  VEHICLE_INSPECTION(Category.TRANSPORT_AND_VEHICLE),
  CHARGING_STATION(Category.TRANSPORT_AND_VEHICLE),
  COMPRESSED_AIR(Category.TRANSPORT_AND_VEHICLE),
  BICYCLE_PARKING(Category.TRANSPORT_AND_VEHICLE),
  BICYCLE_RENTAL(Category.TRANSPORT_AND_VEHICLE),
  BICYCLE_REPAIR_STATION(Category.TRANSPORT_AND_VEHICLE),
  BOAT_RENTAL(Category.TRANSPORT_AND_VEHICLE),
  BOAT_STORAGE(Category.TRANSPORT_AND_VEHICLE),
  BUS_STATION(Category.TRANSPORT_AND_VEHICLE),
  FERRY_TERMINAL(Category.TRANSPORT_AND_VEHICLE),
  TAXI(Category.TRANSPORT_AND_VEHICLE),
  PARKING(Category.TRANSPORT_AND_VEHICLE),
  PARKING_SPACE(Category.TRANSPORT_AND_VEHICLE),
  PARKING_ENTRANCE(Category.TRANSPORT_AND_VEHICLE),
  MOTORCYCLE_PARKING(Category.TRANSPORT_AND_VEHICLE),
  LOADING_DOCK(Category.TRANSPORT_AND_VEHICLE),

  // Animal Services
  ANIMAL_BOARDING(Category.ANIMAL_SERVICES),
  ANIMAL_SHELTER(Category.ANIMAL_SERVICES),
  ANIMAL_TRAINING(Category.ANIMAL_SERVICES),
  VETERINARY(Category.ANIMAL_SERVICES),
  HUNTING_STAND(Category.ANIMAL_SERVICES),

  // Public Facilities
  BENCH(Category.PUBLIC_FACILITIES),
  FOUNTAIN(Category.PUBLIC_FACILITIES),
  DRINKING_WATER(Category.PUBLIC_FACILITIES),
  WATERING_PLACE(Category.PUBLIC_FACILITIES),
  WATER_POINT(Category.PUBLIC_FACILITIES),
  GRIT_BIN(Category.PUBLIC_FACILITIES),
  SANITARY_DUMP_STATION(Category.PUBLIC_FACILITIES),
  SHOWER(Category.PUBLIC_FACILITIES),
  TOILETS(Category.PUBLIC_FACILITIES),
  PUBLIC_BATH(Category.PUBLIC_FACILITIES),
  PUBLIC_BOOKCASE(Category.PUBLIC_FACILITIES),
  MEETING_POINT(Category.PUBLIC_FACILITIES),
  MUSTER_POINT(Category.PUBLIC_FACILITIES),
  TABLE(Category.PUBLIC_FACILITIES),
  SMOKING_AREA(Category.PUBLIC_FACILITIES),
  THERMOMETER(Category.PUBLIC_FACILITIES),
  WEIGHBRIDGE(Category.PUBLIC_FACILITIES),

  // Security & Governance
  POLICE(Category.SECURITY_AND_GOVERNANCE),
  COURTHOUSE(Category.SECURITY_AND_GOVERNANCE),
  LOST_PROPERTY_OFFICE(Category.SECURITY_AND_GOVERNANCE),
  RECEPTION_DESK(Category.SECURITY_AND_GOVERNANCE),

  // Social & Community
  COMMUNITY_CENTRE(Category.SOCIAL_AND_COMMUNITY),
  SOCIAL_CENTRE(Category.SOCIAL_AND_COMMUNITY),
  SOCIAL_FACILITY(Category.SOCIAL_AND_COMMUNITY),
  COWORKING_SPACE(Category.SOCIAL_AND_COMMUNITY),
  CONFERENCE_CENTRE(Category.SOCIAL_AND_COMMUNITY),
  CENTRE(Category.SOCIAL_AND_COMMUNITY),

  // Nightlife
  NIGHTCLUB(Category.NIGHTLIFE);

  private final Category parentCategory;

  SubCategory(Category parentCategory) {
    this.parentCategory = parentCategory;
  }

  public Category getParentCategory() {
    return parentCategory;
  }
}
