server.port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true

spring:
  application.name: landmark-nearify

location-based-landmark:
  service:
    nearby:
      api-url: ${LANDMARK_NEARBY_API_URL}